### ISSUE TITLE
Context menu is not themed on macOS

### ISSUE THREAD

**Issue by vkhitrin** [EliverLara/firefox-sweet-theme#1]
**Issue**:  
On macOS, the context menu (right click) is not themed.
![Unthemed context menu](https://i.imgur.com/lICcqiB.png)
![Unthemed toolbar context menu](https://i.imgur.com/tnUBdDd.png)

**Operating System**: macOS 10.14.6
**Browser Version**: 68.0.1 (64-bit)

**Comment by TwisterMc** [comment]
Ahh. Just noticed this too. Please fix. :)
