### ISSUE TITLE
Not working on Firefox 69.0.2

### ISSUE THREAD

**Issue by DarkcoderSe** [EliverLara/firefox-sweet-theme#12]

**Comment by EliverLara** [comment]
Hi, What exactly is the issue?

**Comment by DarkcoderSe** [comment]
Hey, @EliverLara I installed your script as described in the documentation. Installation completed successfully But, my firefox is still the same. My firefox version is 69.0.2. Your theme working in Office desktop machine where firefox version is 68.0

**Comment by Thoogles** [comment]
Hello @DarkcoderSe I have noticed that the installation script does not work on some of the newer versions, so you will have to rely on the manual method of installation that is documented in the README.md
