### ISSUE TITLE
misplaced titlebar buttons

### ISSUE THREAD

**Issue by justmknyo** [EliverLara/firefox-sweet-theme#16]
After a recent update with firefox, the titlebar buttons joined the tabs bar. I also tested this using a macOS theme of firefox and still the problem persists.

![Screenshot from 2019-12-13 17-47-33](https://user-images.githubusercontent.com/29687366/70791743-a2ce7b00-1dd2-11ea-9dd3-9bc9f01bf17e.png)

**Comment by EliverLara** [comment]
Fixed with #15, thanks to @curbengh.
