### ISSUE TITLE
Titlebar merges on Firefox load

### ISSUE THREAD

**Issue by Nano-Ocelot** [EliverLara/firefox-sweet-theme#17]
The titlebar buttons are merged back into the toolbar everytime Firefox is started. I use a global menu on my desktop panel so I prefer no titlebar buttons on application windows. This application looks really out of place with the titlebar buttons showing. Checking the 'titlebar' button in the 'customize' menu of Firefox will give me the behaviour I want, but every time I restart Firefox the button becomes unchecked. It also fixes the ugly line between the top toolbar and the bookmark bar. Can you allow the theme to respect Firefox's titlebar setting? Or provide an option for it in the theme itself? Or even perhaps just let me know how I can edit the buttons out myself?

**Comment by EliverLara** [comment]
Hi, Do you have any screenshots of the issue?

**Comment by Nano-Ocelot** [comment]
There isn't really anything to screenshot. My issue is that it doesn't respect Firefox's 'title bar' option. Every time I start Firefox this box becomes unticked. Since it becomes unticked, the titlebar merges into the toolbar. I prefer my titlebar to be controlled by my global menu bar on my desktop panel and therefore invisible because I don't need multiple sets of buttons to close my app window. I'll attach a screenshot of the option that I'm talking about.
![Screenshot_20200109_191418](https://user-images.githubusercontent.com/34014750/72115559-7b0cfd00-3315-11ea-9fce-d9e550b807cf.png)

**Comment by EliverLara** [comment]
This is odd,[ it's working fine for me](https://i.imgur.com/BmE9072.gifv) with firefox` v72.0.1`, what's your firefox version?

**Comment by Nano-Ocelot** [comment]
The check box also works for me, but every time you open Firefox you have to recheck that box.  It's not persistent between sessions. My Firefox is also v72.0.1

**Comment by Spinnekop** [comment]
I have the same problem - also using windows buttons in panel. 
![image](https://user-images.githubusercontent.com/31868152/72619652-ae631380-3935-11ea-8712-38a336aa8ab9.png)
Global menu removes the buttons but there is a blank space which only goes when you select title bar.

**Comment by Spinnekop** [comment]
Like this 
![image](https://user-images.githubusercontent.com/31868152/72619825-069a1580-3936-11ea-94e6-bc23222bb014.png)

**Comment by Spinnekop** [comment]
In the section parts/csd.css I put the padding for the windows buttons to 0 and this had the desired effect....

**Comment by Nano-Ocelot** [comment]
I ended up editing a bunch of stuff to get a consistent look with the rest of my theme. Got rid of the window buttons, the line between toolbar and bookmarkbar, edited out the 'unfocused window' lines and fading, and removed the 'bubble' around buttons as well as a few other small tweaks. Now it looks way more consistent with the rest of the sweet theme across my system.

**Comment by Nano-Ocelot** [comment]
I ended up editing a bunch of stuff to make it match my theme too. I edited out the window buttons, the separator between toolbar and bookmarkbar, the 'unfocused window' lines and fading, the 'bubble' buttons on the toolbar, and a few other small tweaks. Now Firefox looks way more consistent with the rest of the Sweet theme on my system.

**Comment by Spinnekop** [comment]
Some lines please?!

**Comment by Nano-Ocelot** [comment]
Oh gosh. I don't remember all the changes at this point. It's easier if I link my files so you and others can use. I'll leave out csd.css since you already found a fix that works for you and my changes are dependent on me also disabling the tabsbar since I use a vertical tabs extension. Just merge this with your 'theme' folder. Make sure you back up yours just in case I messed something up copying these over. https://www.dropbox.com/sh/ymua8gyma3w3nqm/AADesM6C55WyW82N9LejHR0Xa?dl=0

**Comment by Spinnekop** [comment]
Awesome - thank you!

**Comment by LeoFLT** [comment]
In case anyone ever wants to change this setting: go to your profile folder and open user.js on your preferred text editor, then find and delete the line that contains: 
``user_pref("browser.tabs.drawInTitlebar", true);`` 
This setting overrides the Title bar button toggle, so every time you restart Firefox it will come back.

**Comment by Nano-Ocelot** [comment]
Very helpful, thank you.
