### ISSUE TITLE
Bookmark icon spacing

### ISSUE THREAD

**Issue by Spinnekop** [EliverLara/firefox-sweet-theme#19]
Hi
I keep some my bookmark items in the url bar. (from customize move 'bookmark toolbar items')
With this theme they become larger and much more spaced out. If I move it to the tab bar they return to normal size. Any idea how I can fix this please?

Thank you for your design

**Comment by EliverLara** [comment]
Hi, Do you have any screenshots for this issue?

**Comment by Spinnekop** [comment]
No - I stopped using the theme because I couldn't get it to fullscreen on
my version of firefox (72)
