### ISSUE TITLE
Not working on Firefox 72.0.1 

### ISSUE THREAD

**Issue by Mikedeath** [EliverLara/firefox-sweet-theme#21]
@EliverLara I followed the tutorial on how to install it using the script, but firefox remains the same, it doesn't change look

**Comment by Mikedeath** [comment]
Doing it manually made it work, using the script didn't

**Comment by Primokorn** [comment]
Thanks for the heads up.
Installed successfully on Firefox Stable 73.0 with KDE neon User Edition 5.18 x86_64.
