### ISSUE TITLE
url bar drop down menu is transparent/ sizing issues

### ISSUE THREAD

**Issue by joe23rep** [EliverLara/firefox-sweet-theme#22]
hi. after the newest update on my maschine (manjaro kde) the urlbar behaves weird. first off- when i click on it the highlighting frame isnt in the siz of the urlbar anymore but has maybe 20px padding on all sides. secondly the dropdown menu when u enter ur address or search becomes transparent. its pretty much not usable this way. 

just installed ur newest version again to see if the bug is only in my config this way cuz i changed a few things but its still the same.

**Comment by Fahrenheit** [comment]
Same issue.

**Comment by EliverLara** [comment]
Hi, Could you provide some screenshot for this issue? and also your firefox version would be very helpful

**Comment by joe23rep** [comment]
hi. firefox is firefox developer edition version 74.0b6

here are the screenshots- first the layout issue (url bar drops down and when selected adds a padding around the border and then the transparency issue.

![Kazam_screenshot_00004](https://user-images.githubusercontent.com/59401314/75655382-05147a80-5c62-11ea-9a8b-6b19f2f01423.png)
![Kazam_screenshot_00005](https://user-images.githubusercontent.com/59401314/75655396-0c3b8880-5c62-11ea-8b16-6b892313728c.png)

modifications ive done are minimal (changed colors and removed the buttons (minimize, maximize, close). but like i said i tested with the original version and there was the issue the same. 

ive normal firefox running with version 73.0.1 and here everything is fine so im sure its not my mod that causes the issue

**Comment by joe23rep** [comment]
they just released a new version which fixed it
