### ISSUE TITLE
Address bar changed back to default in 75.0

### ISSUE THREAD

**Issue by Thoogles** [EliverLara/firefox-sweet-theme#27]
Hello, with firefox version 75.0 on arch the address bar seems to turn back to default coloring (white), and this seems to happen to non-active tabs as well.

**Comment by Thoogles** [comment]
![2020-04-07-180458_946x184_scrot](https://user-images.githubusercontent.com/63253143/78686771-1b19f880-78fc-11ea-98bd-9766f7914db2.png)

**Comment by SirLotsaLocks** [comment]
yeah this happened to me too on manjaro

**Comment by SirLotsaLocks** [comment]
as a temporary fix, These will work, until they're removed in a future 
release:browser.urlbar.update1 -> false
browser.urlbar.openViewOnFocus -> false
After toggling, restart browser.

**Comment by EliverLara** [comment]
Could you check if it was fixed with the last commit?

**Comment by SirLotsaLocks** [comment]
It seems to fix it yes. Thanks!

**Comment by Thoogles** [comment]
The issue with the Address bar seems to be solved now. Thanks for the quick fix.
The tabs still seem to be default coloured however in the case of non-active tabs, but I will create a separate issue for that one.
