### ISSUE TITLE
URL dropdown is transparent om Manjaro KDE (after updating to newest version)

### ISSUE THREAD

**Issue by LasseKrarup** [EliverLara/firefox-sweet-theme#28]
As of today (9/4-2020) my URL bar is transparent. This happens only using this theme, which has been installed using the manual install method,

I stumbled upon issue #22 and I removed all theme files and did a complete reinstall, but I still see a transparent URL/seach dropdown like this:

![Peek 2020-04-09 18-49](https://user-images.githubusercontent.com/32633899/78921084-a9c17d80-7a94-11ea-83f4-23b30f870a83.gif)

**Comment by SirLotsaLocks** [comment]
yeah, this is due to the new awesomebar update on tuesday
as a temporary fix, These will work, until they're removed in a future
release:browser.urlbar.update1 -> false
browser.urlbar.openViewOnFocus -> false
After toggling, restart browser.

**Comment by EliverLara** [comment]
Could you check if it was fixed with the last commit?

**Comment by LasseKrarup** [comment]
Newest commit fixes the issue

![Peek 2020-04-10 09-46](https://user-images.githubusercontent.com/32633899/78973475-49702180-7b10-11ea-8a83-a222f0d531e7.gif)
