### ISSUE TITLE
Inactive tabs are back to default colour scheme with FF 75.0

### ISSUE THREAD

**Issue by Thoogles** [EliverLara/firefox-sweet-theme#29]
Hello,
The inactive tabs have reverted back to the default colour scheme with firefox 75.0

![2020-04-13-003111_945x73_scrot](https://user-images.githubusercontent.com/63253143/79076718-07f49780-7d05-11ea-9813-49986b20fdc3.png)

**Comment by EliverLara** [comment]
Could you check if that's fixed with the last commit in the [tab-issue branch](https://github.com/EliverLara/firefox-sweet-theme/tree/tab-issue).

**Comment by Thoogles** [comment]
This seems to have fixed the issue with the tabs themselves, however the areas between the tabs, as well as the "new tab" button remains default coloured. Also not sure if the scrollbar used to be default coloured before firefox 75, but that seems to be the case now.

![2020-04-14-234316_1916x113_scrot](https://user-images.githubusercontent.com/63253143/79256554-e3c5c180-7e90-11ea-89de-e5691201e02f.png)

**Comment by Lmasterx001** [comment]
is this only for linux ? in windows when i copy everything to chrome folder and i open firefox i get a black screen.

**Comment by Thoogles** [comment]
Haven't tried the theme on windows so don't really know.

**Comment by EliverLara** [comment]
@Thoogles I've pushed a new commit, could you please check if that fixes the tabs color issue?
