### ISSUE TITLE
Instructions Command Issue

### ISSUE THREAD

**Issue by TwisterMc** [EliverLara/firefox-sweet-theme#3]
When I run `sed -i '1s/^/@import "firefox-sweet-theme\/userChrome.css";\n/' userChrome.css` I get an error that says `sed: 1: "userChrome.css": invalid command code u`

I was able to work around it, but thought I'd share.

**Comment by EliverLara** [comment]
That's weird, I don't get any error when running the command :confused:

**Comment by laermannjan** [comment]
@TwisterMc I assume you're on a mac.

MacOS ships with the BSD version of binaries like `sed` (you can verify with `man sed`, it should say "BSD General Commands Manual" at the very top).
You can install the standard GNU tools with [homebrew](https://formulae.brew.sh/formula/coreutils) and then run the same command with `gsed`.

Of course you could also just copy ﻿the plain text into userChrome.css yourself. ;)
