### ISSUE TITLE
Megabar/urlbar visual glitch

### ISSUE THREAD

**Issue by Nano-Ocelot** [EliverLara/firefox-sweet-theme#37]
In FF 77+ the new urlbar has a visual glitch where the dropdown doesn't align with the frame. You can see a large gap there at the top, the border is also slightly wider on the sides and shorter at the bottom as you can see here.
![Screenshot_20200618_195302](https://user-images.githubusercontent.com/34014750/85082572-53ac3d00-b19d-11ea-8115-900fead6a395.png)

**Comment by aesophor** [comment]
Same on 78.0.2 (64-bit)

![scrot-2020-07-15_085624_1680x1050](https://user-images.githubusercontent.com/32998585/87491291-59048680-c67a-11ea-9c34-fcf893034c6b.png)

**Comment by j0w0** [comment]
same on brand new firefox on latest version

**Comment by EliverLara** [comment]
Fixed!
