### ISSUE TITLE
Not working for 81.0.1

### ISSUE THREAD

**Issue by aonemd** [EliverLara/firefox-sweet-theme#48]
I'm running Firefox 81.0.1, enabled the dark theme from Add-ons, and installed the theme using `sudo ./scripts/install.sh -g`. However, I'm not getting the UI changes as supposed.

Please see screenshot below:

![screenshot_2020-10-12_20:13:15](https://user-images.githubusercontent.com/16504838/95777952-6bb54880-0cc7-11eb-962d-c00bab1384dd.png)

is this not supported on v81 yet?

**Comment by EliverLara** [comment]
Hi, you shouldn't use `sudo` to install it.

**Comment by aonemd** [comment]
Hello,
thanks for the prompt response!

I get permission denied errors if I don't

![screenshot_2020-10-12_20:35:37](https://user-images.githubusercontent.com/16504838/95779553-8937e180-0cca-11eb-8cd4-007281ffd749.png)

**Comment by EliverLara** [comment]
Those errors are for unnecessary files, still not working?

**Comment by aonemd** [comment]
No, same look

![screenshot_2020-10-12_20:46:16](https://user-images.githubusercontent.com/16504838/95780336-00ba4080-0ccc-11eb-9fcb-0421d95943fa.png)

**Comment by EliverLara** [comment]
You could try [uninstalling](https://github.com/EliverLara/firefox-sweet-theme#uninstalling) and doing a [manual installation](https://github.com/EliverLara/firefox-sweet-theme#manual-installation)

**Comment by aonemd** [comment]
I will. Thanks again.

**Comment by aonemd** [comment]
Okay, I did an uninstall and did an manual installation however, I still get the same result; no change in looks.

**Comment by aonemd** [comment]
By the way, in the manual installation instructions, I think you need to add the `-f` option here to force the link if the file already exists.

```bash
ln -sf chrome/firefox-sweet-theme/configuration/user.js ../user.js
```

**Comment by EliverLara** [comment]
That's weird, I'm using it on firefox v81 and it works fine:

![Screenshot_20201012_141514](https://user-images.githubusercontent.com/9838260/95782588-b7e79500-0c95-11eb-93e7-3377f4342d9f.png)

**Comment by aonemd** [comment]
Hey, thanks for the support. I appreciate it.

I removed the config files and reinstalled Firefox and it finally worked.

![screenshot_2020-10-12_21:31:43](https://user-images.githubusercontent.com/16504838/95783589-745f4c00-0cd2-11eb-899b-79c1cb4ffec6.png)
