### ISSUE TITLE
[macOS] "Quit and close tabs" dialog window has weird position

### ISSUE THREAD

**Issue by aesophor** [EliverLara/firefox-sweet-theme#49]
<img width="1440" alt="Screen Shot 2020-10-29 at 12 08 25 PM" src="https://user-images.githubusercontent.com/32998585/97524553-ed9fb400-19df-11eb-9221-6664021de15c.png">

**Comment by SpiCy0** [comment]
Same here, FF 85.0b5, macOS 10.15.7
