### ISSUE TITLE
Window button on the Right

### ISSUE THREAD

**Issue by ujjwalbe** [EliverLara/firefox-sweet-theme#5]
It's on KDE Neon the buttons are on the right side of the window though it's selected on left side. And i disabled the bookmark bar and it's still visible and looks ugly to me. Would be great if you fix those. Or point out what to do i'll fix those. Thanks for this nice work.
Firefox Beta 69

**Comment by ujjwalbe** [comment]
![imgur](https://user-images.githubusercontent.com/29977681/62390109-1936b300-b57f-11e9-8a3e-a6fc4fc1dd08.png)
Here the image

**Comment by EliverLara** [comment]
Please follow [this](https://forum.manjaro.org/t/moving-gtk-window-buttons-to-the-left-on-plasma-kde/74845) instructions to get buttons on left in gtk apps
