### ISSUE TITLE
Bookmarks menu doesn't have an icon

### ISSUE THREAD

**Issue by loque036** [EliverLara/firefox-sweet-theme#50]
I noticed for a while now and it didn't bother me that much, i decided to check if the theme was updated recently and indeed, so i decided to update and oddly enough the bookmarks icon is still missing. 
This is happening on my desktop and laptop, both running firefox 82 under arch linux.

Here's a screenshot of what's happening:
![Screenshot_20201104_221112](https://user-images.githubusercontent.com/30961953/98168774-5eb4ff00-1eeb-11eb-8323-caa417fe190f.png)

**Comment by techmagus** [comment]
Experiencing the same. Fresh install on my end.

Firefox 85.0b5 (64-bit)
Ubuntu 20.04 LTS
