### ISSUE TITLE
Weird glitches

### ISSUE THREAD

**Issue by Tymec** [EliverLara/firefox-sweet-theme#51]
![image](https://user-images.githubusercontent.com/2727109/99857443-8bc00d80-2b8b-11eb-8f23-23e1da749d32.png)
![image](https://user-images.githubusercontent.com/2727109/99857492-a6928200-2b8b-11eb-8a81-62d4972c5172.png)

**Comment by EliverLara** [comment]
Hi, Could you provide more info about your OS please?

**Comment by Tymec** [comment]
![image](https://user-images.githubusercontent.com/2727109/100367211-2db77e00-3002-11eb-86af-9061326bbe53.png)

**Comment by lenonk** [comment]
Installing the Sweet-mars GTK theme by EliverLara solved this issue for me.

**Comment by lenonk** [comment]
For posterity, Plasma 5.20.5 appears to have fixed this issue.
