### ISSUE TITLE
blurry text on tab names

### ISSUE THREAD

**Issue by Nightmare247** [EliverLara/firefox-sweet-theme#53]
I installed your theme manually, but the test on the tabs is kind of blurry. Is this normal?
![image](https://user-images.githubusercontent.com/65822218/103214037-729e3f80-4935-11eb-9364-463c5bf9cb79.png)
![image](https://user-images.githubusercontent.com/65822218/103214047-78942080-4935-11eb-8a4a-8824690cdd51.png)

**Comment by woutiscoding** [comment]
Yes, this is text-shadow and it has been designed this way by intention

**Comment by Nightmare247** [comment]
@woutiscoding thanks for telling, is there any way i can edit the css file to remove the shadow effect?

**Comment by EliverLara** [comment]
@Nightmare247 just open  the `tabsbar.css` file and remove line `73`:

```css

text-shadow: 0px 0px 2px var(--sweet-focused-urlbar-border-color);


```

**Comment by Nightmare247** [comment]
@EliverLara hmm i did that, but nothing seems to change
