### ISSUE TITLE
Context menu when right clicking URL bar is white

### ISSUE THREAD

**Issue by Drose221193** [EliverLara/firefox-sweet-theme#70]
It seems like a recent update has caused the context menu for FF to show up as white in the URL bar recently. First screenshot is image of me right clicking right above the URL bar. Second is right clicking the URL bar. FF version 94.0.2. Relevant system details below that

![image](https://user-images.githubusercontent.com/37414563/144744370-becf5553-7744-4e75-b127-c1f4ce6d99f4.png)

![image](https://user-images.githubusercontent.com/37414563/144744385-dd4bcbc8-0083-486c-8011-0ac557b403de.png)

Operating System: EndeavourOS
KDE Plasma Version: 5.23.4
KDE Frameworks Version: 5.88.0
Qt Version: 5.15.2
Kernel Version: 5.15.6-arch2-1 (64-bit)
Graphics Platform: X11
Processors: 12 × AMD Ryzen 5 3600 6-Core Processor
Memory: 15.6 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1070/PCIe/SSE2

**Comment by dr460nf1r3** [comment]
This is fixed in current Firefox versions.
