### ISSUE TITLE
White border around the edges.

### ISSUE THREAD

**Issue by rr1610** [EliverLara/firefox-sweet-theme#8]
After installing the theme, I get a small, but really horrible white border around the whole window. I'm running Manjaro and Plasma, and its only an issue on Firefox, and only an issue when I instill the sweet theme. Anyone else had and solved this issue? Image below.

[Imgur](https://i.imgur.com/u6MDbmG.png)

**Comment by EliverLara** [comment]
That is caused by the GTK theme that you are using
