### ISSUE TITLE
Visual problems in latest version of firefox

### ISSUE THREAD

**Issue by Aleister-666** [EliverLara/firefox-sweet-theme#84]
In the latest version of firefox after installing the theme from scratch, there are some visual problems with the bookmarks and in the options menu with the zoom. I attached photos of the problem
![problem](https://user-images.githubusercontent.com/58007357/218226254-59fd974d-1f1a-45cc-b8f0-f20b3d1c5eaa.png)

![problem 2](https://user-images.githubusercontent.com/58007357/218226270-eea07ca3-7dec-46e0-ac90-31e135a9717d.png)

![firefox](https://user-images.githubusercontent.com/58007357/218226330-b07cb088-a6fa-4db7-9a93-f236f14855ce.png)

the theme is newly installed (manually)

By the way, excellent browser theme, one of my favorites. my respects you are a pro (y)

**Comment by Vilianexe** [comment]
Yep, same problem, i even tried to edit it in css but it's complex, and `By the way, excellent browser theme, one of my favorites. my respects you are a pro (y)` couldn't agree more

**Comment by AthirsonSilva** [comment]
The same problem occurs on Add-ons section as the image i anexed shows 

![Screenshot from 2023-04-30 16-36-26](https://user-images.githubusercontent.com/84593887/235372944-36dfc7fb-7702-4352-8664-3013bc925bd9.png)
